import { StyleSheet } from 'react-native';
import { AvatarTone } from '../constants/communityData';

export const HUB_HEADER_GRADIENT = ['#092E18', '#0F4A28', '#1A6B3A'];

export const avatarTones: Record<AvatarTone, { bg: string; fg: string }> = {
  green: { bg: '#E4F4EC', fg: '#1A6B3A' },
  amber: { bg: '#FDF5E0', fg: '#B87214' },
  blue: { bg: '#D4E8FC', fg: '#1A5299' },
  red: { bg: '#FDD0D0', fg: '#C02828' },
  purple: { bg: '#EDE8FD', fg: '#4B2EA8' },
};

const BORDER = '#E8F0EC';
const TEXT2 = '#6B8074';

export const hubStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F4F8F5', },
  listContent: { paddingBottom: 96 },
  flex1: { flex: 1 },
  noBottomBorder: { borderBottomWidth: 0 },
  safeAreaModal:{ flex: 1, backgroundColor: '#F4F8F5',marginTop:30 },

  // Header
  header: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 16 },
  headerRow: { flexDirection: 'row', alignItems: 'center' },
  hdrSub: { fontSize: 10, color: 'rgba(255,255,255,0.55)', fontWeight: '600', letterSpacing: 1, textTransform: 'uppercase' },
  hdrTitle: { fontSize: 22, fontWeight: '800', color: '#fff', lineHeight: 26 },
  hdrActions: { marginLeft: 'auto', flexDirection: 'row', gap: 7 },
  hBtn: { width: 36, height: 36, borderRadius: 11, backgroundColor: 'rgba(255,255,255,0.12)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)', alignItems: 'center', justifyContent: 'center' },
  cstat: { flexDirection: 'row', marginTop: 12, backgroundColor: 'rgba(255,255,255,0.1)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)', borderRadius: 12, paddingVertical: 8 },
  cs: { flex: 1, alignItems: 'center', borderRightWidth: 1, borderRightColor: 'rgba(255,255,255,0.12)' },
  csLast: { borderRightWidth: 0 },
  csV: { fontSize: 14, fontWeight: '800', color: '#fff' },
  csL: { fontSize: 8.5, color: 'rgba(255,255,255,0.55)' },

  // Rewards strip
  reward: { marginHorizontal: 14, marginTop: 12, backgroundColor: '#fff', borderWidth: 1, borderColor: BORDER, borderRadius: 14, padding: 12 },
  rewardTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  coinBadge: { width: 42, height: 42, borderRadius: 12, backgroundColor: '#FDF5E0', alignItems: 'center', justifyContent: 'center' },
  coinEmoji: { fontSize: 22 },
  coinVal: { fontSize: 18, fontWeight: '800', color: '#0D1509' },
  coinLabel: { fontSize: 10, color: TEXT2 },
  streakPill: { marginLeft: 'auto', flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#FDECEC', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 5 },
  streakText: { fontSize: 11, fontWeight: '800', color: '#C02828' },
  levelRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 11, marginBottom: 5 },
  levelText: { fontSize: 11, fontWeight: '700', color: '#1C2E18' },
  levelNext: { fontSize: 10, color: TEXT2 },
  levelTrack: { height: 7, backgroundColor: '#E8F0EC', borderRadius: 4, overflow: 'hidden' },
  levelFill: { height: 7, borderRadius: 4, backgroundColor: '#E09830' },

  // Composer
  composer: { marginHorizontal: 14, marginTop: 12, backgroundColor: '#fff', borderWidth: 1, borderColor: BORDER, borderRadius: 14, padding: 11 },
  compTop: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  compInput: { flex: 1, backgroundColor: '#F4F8F5', borderWidth: 1, borderColor: BORDER, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 9 },
  compInputText: { fontSize: 11, color: '#9EB8A8' },
  compActions: { flexDirection: 'row', gap: 6, marginTop: 9, borderTopWidth: 1, borderTopColor: '#F4F8F5', paddingTop: 9 },
  compBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, borderRadius: 9, paddingVertical: 8 },
  compBtnText: { fontSize: 11, fontWeight: '700' },
  compBtnGreen: { backgroundColor: '#E4F4EC' },
  compBtnRed: { backgroundColor: '#FDD0D0' },
  compBtnAmber: { backgroundColor: '#FDF5E0' },
  compBtnPurple: { backgroundColor: '#EDE8FD' },
  compTextGreen: { color: '#1A6B3A' },
  compTextRed: { color: '#C02828' },
  compTextAmber: { color: '#B87214' },
  compTextPurple: { color: '#4B2EA8' },
  createPostRow: { flexDirection: 'row', gap: 10, marginHorizontal: 14, marginTop: 12 },
  createPostCard: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: '#fff', borderWidth: 1, borderColor: BORDER, borderRadius: 14, padding: 12 },
  createPostBtn: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#1A6B3A', alignItems: 'center', justifyContent: 'center' },
  createPostText: { fontSize: 12, fontWeight: '800', color: '#1C2E18' },
  myPostsCard: { width: 96, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: '#E4F4EC', borderRadius: 14, padding: 12 },
  myPostsIconWrap: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  myPostsBtnText: { fontSize: 12, fontWeight: '800', color: '#1A6B3A' },

  // My posts screen
  myPostsHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: BORDER, backgroundColor: '#fff' },
  myPostsTitle: { fontSize: 15, fontWeight: '800', color: '#1C2E18' },
  myPostsLoading: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingTop: 60 },

  // Avatar (shared)
  av: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  avText: { fontSize: 13, fontWeight: '700' },

  // Section header
  section: { paddingHorizontal: 14, paddingTop: 16 },
  sectionFeed: { paddingHorizontal: 14, paddingTop: 16, paddingBottom: 4 },
  sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 9 },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  sectionTitle: { fontSize: 13, fontWeight: '800', color: '#1C2E18' },
  sectionLink: { fontSize: 11, fontWeight: '700', color: '#1A6B3A' },

  // Category chips
  chipsContent: { gap: 7, paddingHorizontal: 14, paddingTop: 14, paddingBottom: 2 },
  chip: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderColor: '#C8D8CC', backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6 },
  chipOn: { backgroundColor: '#0F4A28', borderColor: '#0F4A28' },
  chipText: { fontSize: 11, fontWeight: '600', color: TEXT2 },
  chipTextOn: { color: '#fff' },

  // Spotlight
  spotlight: { marginHorizontal: 14, borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: BORDER, backgroundColor: '#fff' },
  spotImg: { height: 130, justifyContent: 'space-between', padding: 10 },
  spotTagRow: { flexDirection: 'row' },
  spotTag: { backgroundColor: 'rgba(224,152,48,0.95)', color: '#fff', fontSize: 9, fontWeight: '800', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 20, overflow: 'hidden' },
  spotEarn: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(15,74,40,0.92)', paddingHorizontal: 9, paddingVertical: 3, borderRadius: 20 },
  spotEarnText: { color: '#fff', fontSize: 10, fontWeight: '800' },
  spotBody: { padding: 12 },
  spotTitle: { fontSize: 15, fontWeight: '800', color: '#0F4A28', lineHeight: 20 },
  spotSummary: { fontSize: 11, color: TEXT2, marginTop: 4, lineHeight: 16 },
  spotMetaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10 },
  spotAuthor: { fontSize: 11, fontWeight: '600', color: '#3A5040' },
  spotBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#E4F4EC', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6 },
  spotBtnText: { fontSize: 11, fontWeight: '800', color: '#0F4A28' },

  // Contributors
  contribContent: { gap: 9, paddingRight: 14 },
  contrib: { width: 110, backgroundColor: '#fff', borderWidth: 1, borderColor: BORDER, borderRadius: 14, padding: 11, alignItems: 'center' },
  rankBadge: { position: 'absolute', top: 8, left: 8, width: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  rankText: { fontSize: 9, fontWeight: '900', color: '#fff' },
  contribAv: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', marginBottom: 6 },
  contribAvText: { fontSize: 15, fontWeight: '800' },
  contribName: { fontSize: 11, fontWeight: '700', color: '#1C2E18' },
  contribBadge: { fontSize: 9, color: TEXT2, marginTop: 1 },
  contribPts: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: 5, backgroundColor: '#FDF5E0', borderRadius: 20, paddingHorizontal: 8, paddingVertical: 2 },
  contribPtsText: { fontSize: 10, fontWeight: '800', color: '#B87214' },

  // Refer & earn
  refer: { marginHorizontal: 14, marginTop: 16, borderRadius: 16, overflow: 'hidden' },
  referInner: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14 },
  referIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.18)', alignItems: 'center', justifyContent: 'center' },
  referTitle: { fontSize: 14, fontWeight: '800', color: '#fff' },
  referSub: { fontSize: 11, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  referBtn: { backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8 },
  referBtnText: { fontSize: 12, fontWeight: '800', color: '#0F4A28' },

  // Learn guides
  learnContent: { gap: 9, paddingRight: 14 },
  learn: { width: 130, backgroundColor: '#fff', borderWidth: 1, borderColor: BORDER, borderRadius: 12, overflow: 'hidden' },
  learnImg: { height: 64, justifyContent: 'flex-end', padding: 6 },
  learnTag: { alignSelf: 'flex-start', backgroundColor: 'rgba(9,46,24,0.8)', color: '#fff', fontSize: 8, fontWeight: '700', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8, overflow: 'hidden' },
  learnBody: { padding: 9 },
  learnTitle: { fontSize: 11, fontWeight: '700', color: '#1C2E18', lineHeight: 15 },
  learnMeta: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: 3 },
  learnMetaText: { fontSize: 9, color: TEXT2 },

  // Post
  post: { backgroundColor: '#fff', borderWidth: 1, borderColor: BORDER, borderRadius: 16, overflow: 'hidden', marginHorizontal: 14, marginBottom: 12 },
  pHead: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 12, paddingTop: 11, paddingBottom: 8 },
  postMenu: { position: 'absolute', top: 38, right: 10, zIndex: 10, backgroundColor: '#fff', borderWidth: 1, borderColor: BORDER, borderRadius: 12, paddingVertical: 2, shadowColor: '#0F4A28', shadowOpacity: 0.15, shadowOffset: { width: 0, height: 4 }, shadowRadius: 10, elevation: 6 },
  postMenuItem: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 14, paddingVertical: 10 },
  postMenuItemDangerText: { fontSize: 12.5, fontWeight: '700', color: '#C02828' },
  pNameRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  pName: { fontSize: 12, fontWeight: '700', color: '#1C2E18' },
  pMeta: { fontSize: 10, color: TEXT2, marginTop: 1 },
  role: { fontSize: 8, fontWeight: '800', paddingHorizontal: 6, paddingVertical: 1, borderRadius: 8, overflow: 'hidden' },
  roleFarmer: { backgroundColor: '#E4F4EC', color: '#0F4A28' },
  roleOwner: { backgroundColor: '#FDF5E0', color: '#8A5200' },
  pTag: { alignSelf: 'flex-start', marginHorizontal: 12, marginBottom: 8, fontSize: 10, fontWeight: '700', paddingHorizontal: 9, paddingVertical: 3, borderRadius: 20, overflow: 'hidden' },
  pText: { fontSize: 12, color: '#1C2E18', lineHeight: 18, paddingHorizontal: 12, paddingBottom: 4 },
  pLink: { color: '#1A5299', fontWeight: '700', textDecorationLine: 'underline' },
  pReadMore: { fontSize: 11, fontWeight: '800', color: '#1A6B3A', paddingHorizontal: 12, paddingBottom: 10 },
  pMedia: { height: 180, backgroundColor: '#E4F4EC' },
  pGrid: { height: 120, flexDirection: 'row', gap: 2 },
  pGridCell: { flex: 1, backgroundColor: '#E4F4EC' },
  earnBadge: { position: 'absolute', left: 8, top: 8, flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(15,74,40,0.92)', paddingHorizontal: 9, paddingVertical: 3, borderRadius: 20 },
  earnText: { color: '#fff', fontSize: 10, fontWeight: '800' },
  playWrap: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center' },
  playBtn: { width: 48, height: 48, borderRadius: 24, backgroundColor: 'rgba(255,255,255,0.92)', alignItems: 'center', justifyContent: 'center' },
  vidDur: { position: 'absolute', right: 8, bottom: 8, backgroundColor: 'rgba(0,0,0,0.7)', color: '#fff', fontSize: 9, fontWeight: '600', paddingHorizontal: 7, paddingVertical: 2, borderRadius: 6, overflow: 'hidden' },
  pVideoPlayerWrap: { height: 220, backgroundColor: '#000' },
  pVideoCloseBtn: { position: 'absolute', right: 8, top: 8, width: 26, height: 26, borderRadius: 13, backgroundColor: 'rgba(0,0,0,0.6)', alignItems: 'center', justifyContent: 'center' },
  pBar: { flexDirection: 'row', alignItems: 'center', gap: 16, paddingHorizontal: 12, paddingVertical: 9, borderTopWidth: 1, borderTopColor: '#F4F8F5' },

  // Audio (voice-note) post
  audioCard: { flexDirection: 'row', alignItems: 'center', gap: 10, marginHorizontal: 12, marginBottom: 10, backgroundColor: '#F4F8F5', borderRadius: 12, padding: 10 },
  audioPlayBtn: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#4B2EA8', alignItems: 'center', justifyContent: 'center' },
  audioBody: { flex: 1 },
  audioWaveform: { flexDirection: 'row', alignItems: 'center', gap: 2, height: 26 },
  audioWaveBar: { width: 3, borderRadius: 2, backgroundColor: '#4B2EA8' },
  audioDuration: { fontSize: 10, color: TEXT2, marginTop: 4 },
  audioInlinePlayer: { height: 40 },

  // Poll post
  pollCard: { marginHorizontal: 12, marginBottom: 10, backgroundColor: '#F4F8F5', borderRadius: 16, padding: 14 },
  pollQuestion: { fontSize: 15, fontWeight: '800', color: '#1C2E18', marginBottom: 8, lineHeight: 20 },
  pollSubtitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 14 },
  pollSubtitleText: { fontSize: 11.5, color: TEXT2, fontWeight: '600' },
  pollOptionRow: { marginBottom: 14 },
  pollOptionTopRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 7 },
  pollOptionLabel: { flex: 1, fontSize: 13.5, color: '#1C2E18', fontWeight: '600' },
  pollOptionLabelVoted: { fontWeight: '800', color: '#0F4A28' },
  pollOptionCount: { fontSize: 12.5, color: TEXT2, fontWeight: '700' },
  pollOptionTrack: { height: 7, borderRadius: 4, backgroundColor: '#fff', overflow: 'hidden', borderWidth: 1, borderColor: BORDER },
  pollOptionFill: { height: 7, borderRadius: 4, backgroundColor: '#1A6B3A' },
  pollFooterRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 2, paddingTop: 10, borderTopWidth: 1, borderTopColor: BORDER },
  pollFooterTime: { fontSize: 10.5, color: TEXT2, fontWeight: '600' },
  pollFooterViewVotes: { fontSize: 12, fontWeight: '800', color: '#1A6B3A' },

  pAct: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  pActText: { fontSize: 11, fontWeight: '600', color: TEXT2 },
  pActTextLiked: { color: '#C02828' },
  pSave: { marginLeft: 'auto' },
  pReadStory: { flexDirection: 'row', alignItems: 'center', gap: 4, marginLeft: 'auto' },
  pReadStoryText: { fontSize: 12, fontWeight: '700', color: '#1A6B3A' },

  // Blog reader (full story view)
  readerHeader: { flexDirection: 'row', alignItems: 'center', padding: 16 },
  readerCover: { width: '100%', height: 220, backgroundColor: '#E4F4EC' },
  readerTitle: { fontSize: 20, fontWeight: '800', color: '#1C2E18', paddingHorizontal: 16, marginTop: 14, lineHeight: 27 },
  readerMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 16, marginTop: 14 },
  readerMetaName: { fontSize: 13, fontWeight: '700', color: '#1C2E18' },
  readerMetaSub: { fontSize: 11.5, color: TEXT2, marginTop: 1 },
  readerParagraph: { fontSize: 14, color: '#1C2E18', lineHeight: 21, paddingHorizontal: 16, marginTop: 16 },

  // Stories tray
  storyTray: { flexDirection: 'row', paddingHorizontal: 14, paddingTop: 14, paddingBottom: 4, gap: 14 },
  storyItem: { alignItems: 'center', width: 64 },
  storyRingWrap: { width: 62, height: 62, borderRadius: 31, alignItems: 'center', justifyContent: 'center', borderWidth: 2.5, borderColor: '#1A6B3A' },
  storyRingEmpty: { borderWidth: 2, borderColor: '#C8D8CC', borderStyle: 'dashed' },
  storyAvatarInner: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', backgroundColor: '#E4F4EC' },
  storyAvatarImg: { width: 54, height: 54, borderRadius: 27 },
  storyAddBadge: { position: 'absolute', right: -2, bottom: -2, width: 22, height: 22, borderRadius: 11, backgroundColor: '#1A6B3A', borderWidth: 2, borderColor: '#F4F8F5', alignItems: 'center', justifyContent: 'center' },
  storyLabel: { fontSize: 10, fontWeight: '600', color: '#3A5040', marginTop: 5, textAlign: 'center' },

  // Modal shared
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)' },
  sheet: { backgroundColor: '#fff', borderTopLeftRadius: 22, borderTopRightRadius: 22, paddingHorizontal: 18, paddingTop: 10, paddingBottom: 30 },
  sheetHandle: { alignSelf: 'center', width: 42, height: 5, borderRadius: 3, backgroundColor: '#D7E2DB', marginBottom: 14 },
  sheetTitle: { fontSize: 18, fontWeight: '800', color: '#0D1509' },
  sheetSub: { fontSize: 12, color: TEXT2, marginTop: 3, marginBottom: 16, lineHeight: 17 },

  // Story composer
  sourceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  sourceBtn: { width: '47%', alignItems: 'center', gap: 7, backgroundColor: '#F4F8F5', borderWidth: 1, borderColor: BORDER, borderRadius: 14, paddingVertical: 18 },
  sourceIcon: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  sourceLabel: { fontSize: 12, fontWeight: '700', color: '#1C2E18' },
  sheetCancel: { alignSelf: 'center', marginTop: 16, paddingVertical: 6, paddingHorizontal: 16 },
  sheetCancelText: { fontSize: 13, fontWeight: '700', color: TEXT2 },

  previewMediaImg: { width: '100%', height: 320, borderRadius: 16, backgroundColor: '#E4F4EC' },
  previewVideoCard: { width: '100%', height: 320, borderRadius: 16, backgroundColor: '#0F4A28', alignItems: 'center', justifyContent: 'center', gap: 8 },
  previewVideoText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  previewMeta: { fontSize: 11, color: TEXT2, marginTop: 10, textAlign: 'center' },
  previewActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  previewBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 12, paddingVertical: 13 },
  previewDiscard: { backgroundColor: '#F4F8F5', borderWidth: 1, borderColor: BORDER },
  previewDiscardText: { fontSize: 13, fontWeight: '700', color: '#6B8074' },
  previewConfirm: { backgroundColor: '#1A6B3A' },
  previewConfirmText: { fontSize: 13, fontWeight: '800', color: '#fff' },

  // Story viewer (full-screen)
  viewerRoot: { flex: 1, backgroundColor: '#000' },
  viewerProgressRow: { flexDirection: 'row', gap: 4, paddingHorizontal: 10, paddingTop: 12 },
  viewerProgressTrack: { flex: 1, height: 3, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.3)', overflow: 'hidden' },
  viewerProgressFill: { height: 3, backgroundColor: '#fff' },
  viewerHeaderRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingTop: 10, paddingBottom: 6 },
  viewerHeaderText: { color: '#fff', fontSize: 12, fontWeight: '700', marginLeft: 8 },
  viewerClose: { marginLeft: 'auto', padding: 4 },
  viewerMediaWrap: { flex: 1 },
  viewerImage: { flex: 1 },
  viewerVideoWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10 },
  viewerVideoLabel: { color: '#fff', fontSize: 14, fontWeight: '700' },
  viewerTapZones: { ...StyleSheet.absoluteFillObject, flexDirection: 'row' },
  viewerTapZone: { flex: 1 },

  // Post composer (full-screen)
  composerHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: BORDER },
  composerBackButton: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#E7F3EA', alignItems: 'center', justifyContent: 'center' },
  composerBody: { flex: 1, padding: 16 },

  // Post type picker (first screen of the composer)
  composerPickerTitle: { fontSize: 16, fontWeight: '800', color: '#1C2E18', marginBottom: 14 },
  composerTypeCard: { flexDirection: 'row', alignItems: 'center', gap: 14, borderWidth: 1.5, borderColor: '#E4F4EC', backgroundColor: '#F4F8F5', borderRadius: 16, padding: 16, marginBottom: 12 },
  composerTypeIconWrap: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  composerTypeCardTitle: { fontSize: 13.5, fontWeight: '700', color: '#1C2E18' },
  composerTypeCardDesc: { fontSize: 11.5, color: TEXT2, marginTop: 2 },
  composerAuthorRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  composerAuthorName: { fontSize: 13, fontWeight: '700', color: '#1C2E18' },
  composerAudiencePill: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#F4F8F5', borderRadius: 12, paddingHorizontal: 9, paddingVertical: 3, marginTop: 3, alignSelf: 'flex-start' },
  composerAudiencePillText: { fontSize: 11, color: '#3A5040' },
  composerTitleInput: { fontSize: 17, fontWeight: '700', color: '#1C2E18', borderBottomWidth: 1.5, borderBottomColor: BORDER, paddingBottom: 8, marginBottom: 14 },
  composerInput: { fontSize: 14, color: '#1C2E18', minHeight: 70, textAlignVertical: 'top', lineHeight: 20 },
  composerCategoryLabel: { fontSize: 11, fontWeight: '700', color: TEXT2, marginTop: 16, marginBottom: 6 },
  composerMediaWrap: { marginTop: 14, borderRadius: 14, overflow: 'hidden' },
  composerMediaImg: { width: '100%', height: 220, backgroundColor: '#E4F4EC' },
  composerVideoCard: { width: '100%', height: 220, backgroundColor: '#0F4A28', alignItems: 'center', justifyContent: 'center', gap: 8 },
  composerVoiceCard: { width: '100%', height: 220, backgroundColor: '#4B2EA8', alignItems: 'center', justifyContent: 'center', gap: 8 },
  composerMediaRemove: { position: 'absolute', top: 8, right: 8, width: 28, height: 28, borderRadius: 14, backgroundColor: 'rgba(0,0,0,0.55)', alignItems: 'center', justifyContent: 'center' },
  composerBigAttachBox: { marginTop: 14, borderWidth: 1.5, borderColor: '#C7DBCE', borderStyle: 'dashed', borderRadius: 14, alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 28 },
  composerBigAttachBoxSmall: { paddingVertical: 18 },
  composerBigAttachText: { fontSize: 12, color: '#3A5040' },

  // Poll compose fields
  composerOptionsLabel: { fontSize: 11, fontWeight: '700', color: TEXT2, marginTop: 18, marginBottom: 8 },
  composerOptionRow: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 9 },
  composerOptionDot: { width: 20, height: 20, borderRadius: 6, borderWidth: 1.5, borderColor: BORDER },
  composerOptionInput: { flex: 1, backgroundColor: '#F4F8F5', borderWidth: 1, borderColor: BORDER, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, fontSize: 12.5, color: '#1C2E18' },
  composerOptionRemove: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center' },
  composerAddOption: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 9, paddingHorizontal: 2 },
  composerAddOptionText: { fontSize: 12, fontWeight: '700', color: '#1A6B3A' },

  // Post-type filter row (Community feed)
  filterRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, marginTop: 2, marginBottom: 4, gap: 8 },
  filterScrollContent: { gap: 7, paddingRight: 8 },
  filterFunnelBtn: { width: 34, height: 34, borderRadius: 10, backgroundColor: '#E4F4EC', borderWidth: 1, borderColor: '#1A6B3A', alignItems: 'center', justifyContent: 'center' },
  filterChip: { borderWidth: 1.5, borderColor: '#D4E8FC', backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6 },
  filterChipOn: { backgroundColor: '#1A5299', borderColor: '#1A5299' },
  filterChipText: { fontSize: 11, fontWeight: '700', color: '#1A5299' },
  filterChipTextOn: { color: '#fff' },
  filterCaption: { fontSize: 10, color: TEXT2, paddingHorizontal: 14, marginBottom: 10, lineHeight: 14 },

  // Voice recorder modal
  voiceStateBox: { alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 22 },
  voiceStateText: { fontSize: 12.5, color: TEXT2, textAlign: 'center', lineHeight: 18, paddingHorizontal: 12 },
  voiceMicPulse: { width: 68, height: 68, borderRadius: 34, backgroundColor: '#C02828', alignItems: 'center', justifyContent: 'center' },
  voiceTimer: { fontSize: 20, fontWeight: '800', color: '#0D1509' },
  voiceStopBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#0D1509', borderRadius: 20, paddingHorizontal: 18, paddingVertical: 9 },
  voiceStopText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  voiceRetryBtn: { marginTop: 4, backgroundColor: '#1A6B3A', borderRadius: 20, paddingHorizontal: 16, paddingVertical: 8 },
  voiceRetryText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  voicePreviewPlayer: { width: '100%', marginTop: 4 },
  voiceOrDivider: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 6, marginBottom: 2 },
  voiceOrLine: { flex: 1, height: 1, backgroundColor: BORDER },
  voiceOrText: { fontSize: 10, fontWeight: '800', color: TEXT2, letterSpacing: 0.5 },
  voiceUploadBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderWidth: 1.5, borderColor: '#C7DBCE', borderStyle: 'dashed', borderRadius: 14, paddingVertical: 12, marginTop: 10 },
  voiceUploadBtnText: { fontSize: 12.5, fontWeight: '700', color: '#1A6B3A' },

  // Comments modal
  commentsHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: BORDER },
  commentsTitle: { fontSize: 15, fontWeight: '800', color: '#1C2E18' },
  commentsList: { flex: 1 },
  commentsListContent: { padding: 16, paddingBottom: 8 },
  commentsLoading: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingTop: 60 },
  commentsEmpty: { alignItems: 'center', paddingTop: 60, paddingHorizontal: 24 },
  commentsEmptyText: { fontSize: 12.5, color: TEXT2, textAlign: 'center', marginTop: 8, lineHeight: 18 },
  commentRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  commentBody: { flex: 1, backgroundColor: '#F4F8F5', borderRadius: 14, borderTopLeftRadius: 4, padding: 10 },
  commentNameRow: { flexDirection: 'row', alignItems: 'center' },
  commentName: { fontSize: 12, fontWeight: '700', color: '#1C2E18' },
  commentMenuBtn: { marginLeft: 'auto', padding: 2 },
  commentText: { fontSize: 12.5, color: '#1C2E18', lineHeight: 18, marginTop: 2 },
  commentTime: { fontSize: 10, color: TEXT2, marginTop: 5, marginLeft: 2 },
  commentMenu: { position: 'absolute', top: 20, right: 0, zIndex: 10, backgroundColor: '#fff', borderWidth: 1, borderColor: BORDER, borderRadius: 12, paddingVertical: 2, shadowColor: '#0F4A28', shadowOpacity: 0.15, shadowOffset: { width: 0, height: 4 }, shadowRadius: 10, elevation: 6 },
  commentMenuItem: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 14, paddingVertical: 10 },
  commentMenuItemText: { fontSize: 12.5, fontWeight: '700', color: '#1C2E18' },
  commentMenuItemDangerText: { fontSize: 12.5, fontWeight: '700', color: '#C02828' },
  commentEditingBanner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FDF5E0', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 7, marginHorizontal: 16, marginBottom: 8 },
  commentEditingText: { fontSize: 11, fontWeight: '700', color: '#8A5200' },
  commentEditingCancel: { fontSize: 11, fontWeight: '800', color: '#8A5200' },
  commentInputBar: { flexDirection: 'row', alignItems: 'flex-end', gap: 8, paddingHorizontal: 16, paddingVertical: 10, borderTopWidth: 1, borderTopColor: BORDER, backgroundColor: '#fff' },
  commentInput: { flex: 1, maxHeight: 90, backgroundColor: '#F4F8F5', borderWidth: 1, borderColor: BORDER, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 9, fontSize: 13, color: '#1C2E18', textAlign: 'left', writingDirection: 'ltr' },
  commentSendBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#0F4A28', alignItems: 'center', justifyContent: 'center' },
  commentSendBtnDisabled: { opacity: 0.4 },
});
