import React, { useCallback } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation, useRoute, RouteProp } from '@react-navigation/native';
import Ionicons from 'react-native-vector-icons/Ionicons';
import { useLeases } from '../context/LeaseContext';
import { useAuth } from '../context/AuthContext';
import { LEASE_TYPE_MAP } from '../constants/leaseTypes';
import { colors } from '../theme/tokens';

type ParamList = { AgreementSign: { agreementId: string } };

const G = colors.deepGreen;

function SignatureBlock({ name, role, signed }: { name: string; role: string; signed: boolean }) {
  return (
    <View style={[styles.signBox, signed && styles.signBoxDone]}>
      <Text style={styles.signRole}>{role}</Text>
      {signed ? (
        <View style={styles.signedRow}>
          <Ionicons name="checkmark-circle" size={18} color={G.g3} />
          <Text style={styles.signedName}>{name}</Text>
        </View>
      ) : (
        <Text style={styles.pendingName}>Awaiting signature</Text>
      )}
    </View>
  );
}

export default function AgreementScreen() {
  const navigation = useNavigation<any>();
  const route = useRoute<RouteProp<ParamList, 'AgreementSign'>>();
  const { user } = useAuth();
  const { getAgreementById, signAgreementAsFarmer } = useLeases();

  const agreement = getAgreementById(route.params.agreementId);
  const isOwnerViewer = (user as { role?: string })?.role === 'owner';

  const onSign = useCallback(() => {
    if (!agreement) return;
    Alert.alert('Sign this agreement?', 'By signing, you accept the lease terms shown above.', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Accept & Sign',
        onPress: () => {
          signAgreementAsFarmer(agreement.id);
          Alert.alert('Lease booked ✓', 'Both parties have signed. Your lease is now active!', [
            { text: 'View my lease', onPress: () => navigation.navigate('MyActiveLeases') },
          ]);
        },
      },
    ]);
  }, [agreement, signAgreementAsFarmer, navigation]);

  if (!agreement) {
    return (
      <SafeAreaView style={styles.safe} edges={['top']}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()} hitSlop={8}>
            <Ionicons name="arrow-back" size={22} color="#fff" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Agreement</Text>
        </View>
        <View style={styles.empty}>
          <Ionicons name="document-outline" size={40} color={G.n6} />
          <Text style={styles.emptyText}>Agreement not found.</Text>
        </View>
      </SafeAreaView>
    );
  }

  const t = LEASE_TYPE_MAP[agreement.typeId];
  const active = agreement.status === 'active';
  const rows = [
    ...agreement.fullTerms,
    { label: 'Tenure', value: agreement.tenure },
    { label: 'Available from', value: agreement.availableFrom },
  ];

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} hitSlop={8}>
          <Ionicons name="arrow-back" size={22} color="#fff" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Lease Agreement</Text>
        {active && <View style={styles.activePill}><Text style={styles.activePillText}>ACTIVE</Text></View>}
      </View>

      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        {/* Document */}
        <View style={styles.doc}>
          <View style={styles.docHead}>
            <Text style={styles.docEmoji}>{t.emoji}</Text>
            <View style={{ flex: 1 }}>
              <Text style={styles.docTitle}>{t.name} Agreement</Text>
              <Text style={styles.docLand}>{agreement.landTitle}</Text>
            </View>
          </View>

          <View style={styles.parties}>
            <Text style={styles.partyText}>
              Between <Text style={styles.bold}>{agreement.ownerName}</Text> (Owner) and{' '}
              <Text style={styles.bold}>{agreement.farmerName}</Text> (Farmer)
            </Text>
          </View>

          <Text style={styles.termsHead}>Terms</Text>
          {rows.map(r => (
            <View key={r.label} style={styles.termRow}>
              <Text style={styles.termLabel}>{r.label}</Text>
              <Text style={styles.termValue}>{r.value}</Text>
            </View>
          ))}

          <Text style={styles.fine}>
            This is a digital lease record generated by GreenPlot. Both parties agree to the terms above for the stated tenure.
          </Text>
        </View>

        {/* Signatures */}
        <Text style={styles.sectionLabel}>Signatures</Text>
        <View style={styles.signRow}>
          <SignatureBlock name={agreement.ownerName} role="Owner" signed={agreement.ownerSigned} />
          <SignatureBlock name={agreement.farmerName} role="Farmer" signed={agreement.farmerSigned} />
        </View>

        {/* Action */}
        {active ? (
          <View style={styles.activeBox}>
            <Ionicons name="checkmark-done-circle" size={22} color={G.g3} />
            <Text style={styles.activeText}>Lease active since {agreement.startDate}</Text>
          </View>
        ) : isOwnerViewer ? (
          <View style={styles.waitBox}>
            <Ionicons name="time-outline" size={18} color={G.a3} />
            <Text style={styles.waitText}>You’ve signed. Waiting for {agreement.farmerName} to sign.</Text>
          </View>
        ) : agreement.farmerSigned ? (
          <View style={styles.waitBox}>
            <Ionicons name="time-outline" size={18} color={G.a3} />
            <Text style={styles.waitText}>You’ve signed. Finalising the lease…</Text>
          </View>
        ) : (
          <TouchableOpacity style={styles.signBtn} onPress={onSign} activeOpacity={0.85}>
            <Ionicons name="create" size={18} color="#fff" />
            <Text style={styles.signBtnText}>Accept & Sign agreement</Text>
          </TouchableOpacity>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: G.n8 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: G.g2, paddingHorizontal: 16, paddingVertical: 14 },
  headerTitle: { fontSize: 18, fontWeight: '800', color: '#fff' },
  activePill: { marginLeft: 'auto', backgroundColor: G.g4, borderRadius: 20, paddingHorizontal: 9, paddingVertical: 3 },
  activePillText: { color: '#fff', fontSize: 10, fontWeight: '800' },
  scroll: { padding: 14, paddingBottom: 30 },
  doc: { backgroundColor: '#fff', borderWidth: 1, borderColor: G.n7, borderRadius: 14, padding: 16 },
  docHead: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  docEmoji: { fontSize: 26 },
  docTitle: { fontSize: 17, fontWeight: '800', color: G.g1 },
  docLand: { fontSize: 12, color: G.n4, marginTop: 1 },
  parties: { backgroundColor: G.n8, borderRadius: 10, padding: 11, marginBottom: 14 },
  partyText: { fontSize: 12, color: G.n2, lineHeight: 18 },
  bold: { fontWeight: '800', color: G.g1 },
  termsHead: { fontSize: 11, fontWeight: '800', color: G.n4, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8 },
  termRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: G.n8, gap: 12 },
  termLabel: { fontSize: 12, color: G.n4, flexShrink: 0 },
  termValue: { fontSize: 12, color: G.n2, fontWeight: '600', flex: 1, textAlign: 'right' },
  fine: { fontSize: 10, color: G.n4, lineHeight: 15, marginTop: 12, fontStyle: 'italic' },
  sectionLabel: { fontSize: 11, fontWeight: '800', color: G.n4, textTransform: 'uppercase', letterSpacing: 0.5, marginTop: 16, marginBottom: 9 },
  signRow: { flexDirection: 'row', gap: 10 },
  signBox: { flex: 1, backgroundColor: '#fff', borderWidth: 1, borderColor: G.n7, borderRadius: 12, padding: 13, minHeight: 74, justifyContent: 'center' },
  signBoxDone: { borderColor: '#A8D8B8', backgroundColor: G.g7 },
  signRole: { fontSize: 10, fontWeight: '700', color: G.n4, textTransform: 'uppercase', marginBottom: 6 },
  signedRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  signedName: { fontSize: 13, fontWeight: '800', color: G.g2 },
  pendingName: { fontSize: 12, color: G.a3, fontWeight: '600' },
  signBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: G.g2, borderRadius: 12, paddingVertical: 15, marginTop: 16 },
  signBtnText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  activeBox: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: G.g7, borderRadius: 12, padding: 14, marginTop: 16, justifyContent: 'center' },
  activeText: { color: G.g2, fontSize: 13, fontWeight: '800' },
  waitBox: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: G.a7, borderRadius: 12, padding: 14, marginTop: 16, justifyContent: 'center' },
  waitText: { color: G.a3, fontSize: 12, fontWeight: '700', flexShrink: 1 },
  empty: { alignItems: 'center', paddingVertical: 60, gap: 12 },
  emptyText: { fontSize: 13, color: G.n4 },
});
