import { Job } from '../types';

// Default farmer/farm for demo - in production this would come from auth
const DEFAULT_FARMER_ID = 'F001';
const DEFAULT_FARMER_NAME = 'Rajesh Kulkarni';
const DEFAULT_FARM_NAME = 'Green Valley Farm';

export const MOCK_JOBS: Job[] = [
  {
    jobId: 'J001',
    farmerId: DEFAULT_FARMER_ID,
    farmerName: DEFAULT_FARMER_NAME,
    farmName: DEFAULT_FARM_NAME,
    workType: 'Harvesting',
    cropType: 'Sugarcane',
    acres: 5,
    workersNeeded: 8,
    workersHired: 3,
    wagePerDay: 500,
    workDate: '2025-02-15',
    location: {
      latitude: 16.5909,
      longitude: 74.9171,
      address: 'Sangli Road, Kolhapur',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    notes: 'Need experienced workers for sugarcane harvest',
    status: 'open',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    jobId: 'J002',
    farmerId: 'F002',
    farmerName: 'Suresh Patil',
    farmName: 'Patil Farm',
    workType: 'Weeding',
    cropType: 'Cotton',
    acres: 3,
    workersNeeded: 5,
    workersHired: 0,
    wagePerDay: 400,
    workDate: '2025-02-12',
    location: {
      latitude: 16.5940,
      longitude: 74.9220,
      address: 'Ichalkaranji',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'open',
    createdAt: '2025-01-30T08:00:00Z',
  },
  {
    jobId: 'J003',
    farmerId: 'F003',
    farmerName: 'Anita Deshmukh',
    farmName: 'Deshmukh Agri',
    workType: 'Planting',
    cropType: 'Tomato',
    acres: 2,
    workersNeeded: 6,
    workersHired: 4,
    wagePerDay: 450,
    workDate: '2025-02-18',
    location: {
      latitude: 16.5860,
      longitude: 74.9100,
      address: 'Hatkanangale',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    notes: 'Tomato transplanting - morning shift',
    status: 'in_progress',
    createdAt: '2025-02-05T09:00:00Z',
  },
  {
    jobId: 'J004',
    farmerId: DEFAULT_FARMER_ID,
    farmerName: DEFAULT_FARMER_NAME,
    farmName: DEFAULT_FARM_NAME,
    workType: 'Plowing',
    cropType: 'Wheat',
    acres: 4,
    workersNeeded: 2,
    workersHired: 0,
    wagePerDay: 550,
    workDate: '2025-02-20',
    location: {
      latitude: 16.5920,
      longitude: 74.9180,
      address: 'Kolhapur Rural',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'open',
    createdAt: '2025-02-06T11:00:00Z',
  },
  {
    jobId: 'J005',
    farmerId: 'F004',
    farmerName: 'Vikram Jadhav',
    farmName: 'Jadhav Farms',
    workType: 'Irrigation',
    cropType: 'Onion',
    acres: 6,
    workersNeeded: 4,
    workersHired: 2,
    wagePerDay: 420,
    workDate: '2025-02-14',
    location: {
      latitude: 16.5780,
      longitude: 74.9050,
      address: 'Shirol',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'open',
    createdAt: '2025-02-02T14:00:00Z',
  },
  {
    jobId: 'J006',
    farmerId: 'F005',
    farmerName: 'Priya Kulkarni',
    farmName: 'Priya Agro',
    workType: 'Spraying',
    cropType: 'Cotton',
    acres: 4,
    workersNeeded: 3,
    workersHired: 0,
    wagePerDay: 480,
    workDate: '2025-02-16',
    location: {
      latitude: 16.5950,
      longitude: 74.9280,
      address: 'Gadhinglaj',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    notes: 'Pesticide spraying - bring masks',
    status: 'open',
    createdAt: '2025-02-04T07:00:00Z',
  },
  {
    jobId: 'J007',
    farmerId: 'F002',
    farmerName: 'Suresh Patil',
    farmName: 'Patil Farm',
    workType: 'Transplanting',
    cropType: 'Paddy',
    acres: 3,
    workersNeeded: 10,
    workersHired: 7,
    wagePerDay: 400,
    workDate: '2025-02-10',
    location: {
      latitude: 16.5935,
      longitude: 74.9200,
      address: 'Kagal',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'in_progress',
    createdAt: '2025-01-28T10:00:00Z',
  },
  {
    jobId: 'J008',
    farmerId: DEFAULT_FARMER_ID,
    farmerName: DEFAULT_FARMER_NAME,
    farmName: DEFAULT_FARM_NAME,
    workType: 'Threshing',
    cropType: 'Wheat',
    acres: 5,
    workersNeeded: 6,
    workersHired: 0,
    wagePerDay: 520,
    workDate: '2025-02-22',
    location: {
      latitude: 16.5915,
      longitude: 74.9165,
      address: 'Sangli Road',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'open',
    createdAt: '2025-02-07T08:00:00Z',
  },
  {
    jobId: 'J009',
    farmerId: 'F006',
    farmerName: 'Ramesh Shinde',
    farmName: 'Shinde Farm',
    workType: 'Harvesting',
    cropType: 'Grapes',
    acres: 8,
    workersNeeded: 12,
    workersHired: 5,
    wagePerDay: 550,
    workDate: '2025-02-19',
    location: {
      latitude: 16.5820,
      longitude: 74.9020,
      address: 'Panhala',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    notes: 'Grape harvest - early morning start',
    status: 'open',
    createdAt: '2025-02-03T12:00:00Z',
  },
  {
    jobId: 'J010',
    farmerId: 'F007',
    farmerName: 'Lata Gaikwad',
    farmName: 'Gaikwad Agri',
    workType: 'Weeding',
    cropType: 'Soybean',
    acres: 4,
    workersNeeded: 6,
    workersHired: 2,
    wagePerDay: 380,
    workDate: '2025-02-13',
    location: {
      latitude: 16.5970,
      longitude: 74.9320,
      address: 'Chandgad',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'open',
    createdAt: '2025-02-01T15:00:00Z',
  },
  {
    jobId: 'J011',
    farmerId: 'F008',
    farmerName: 'Dinesh Mane',
    farmName: 'Mane Farms',
    workType: 'Planting',
    cropType: 'Maize',
    acres: 7,
    workersNeeded: 8,
    workersHired: 0,
    wagePerDay: 430,
    workDate: '2025-02-21',
    location: {
      latitude: 16.5840,
      longitude: 74.9080,
      address: 'Radhanagari',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'open',
    createdAt: '2025-02-05T09:00:00Z',
  },
  {
    jobId: 'J012',
    farmerId: 'F003',
    farmerName: 'Anita Deshmukh',
    farmName: 'Deshmukh Agri',
    workType: 'Harvesting',
    cropType: 'Chili',
    acres: 2,
    workersNeeded: 4,
    workersHired: 4,
    wagePerDay: 480,
    workDate: '2025-02-08',
    location: {
      latitude: 16.5855,
      longitude: 74.9110,
      address: 'Hatkanangale',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'completed',
    createdAt: '2025-01-25T10:00:00Z',
  },
  {
    jobId: 'J013',
    farmerId: 'F004',
    farmerName: 'Vikram Jadhav',
    farmName: 'Jadhav Farms',
    workType: 'Plowing',
    cropType: 'Groundnut',
    acres: 5,
    workersNeeded: 3,
    workersHired: 0,
    wagePerDay: 540,
    workDate: '2025-02-25',
    location: {
      latitude: 16.5775,
      longitude: 74.9060,
      address: 'Shirol',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'open',
    createdAt: '2025-02-08T07:00:00Z',
  },
  {
    jobId: 'J014',
    farmerId: DEFAULT_FARMER_ID,
    farmerName: DEFAULT_FARMER_NAME,
    farmName: DEFAULT_FARM_NAME,
    workType: 'Spraying',
    cropType: 'Sugarcane',
    acres: 5,
    workersNeeded: 4,
    workersHired: 1,
    wagePerDay: 460,
    workDate: '2025-02-17',
    location: {
      latitude: 16.5905,
      longitude: 74.9175,
      address: 'Sangli Road',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'open',
    createdAt: '2025-02-06T13:00:00Z',
  },
  {
    jobId: 'J015',
    farmerId: 'F009',
    farmerName: 'Sunita Kamble',
    farmName: 'Kamble Agro',
    workType: 'Irrigation',
    cropType: 'Turmeric',
    acres: 3,
    workersNeeded: 3,
    workersHired: 0,
    wagePerDay: 410,
    workDate: '2025-02-24',
    location: {
      latitude: 16.5990,
      longitude: 74.9340,
      address: 'Bhudargad',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'open',
    createdAt: '2025-02-07T11:00:00Z',
  },
  {
    jobId: 'J016',
    farmerId: 'F010',
    farmerName: 'Arun Chavan',
    farmName: 'Chavan Farms',
    workType: 'Transplanting',
    cropType: 'Paddy',
    acres: 4,
    workersNeeded: 8,
    workersHired: 3,
    wagePerDay: 420,
    workDate: '2025-02-11',
    location: {
      latitude: 16.5885,
      longitude: 74.9090,
      address: 'Shahuwadi',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
    status: 'open',
    createdAt: '2025-02-02T08:00:00Z',
  },
];
