import { Labor } from '../types';

export const MOCK_LABORERS: Labor[] = [
  {
    laborId: 'L001',
    name: 'Ramesh Kumar',
    phone: '+91 98765 43210',
    skills: ['Harvesting', 'Weeding', 'Planting'],
    wageExpected: 450,
    rating: 4.5,
    experienceYears: 8,
    location: {
      latitude: 16.5921,
      longitude: 74.9182,
      address: 'Sangli Road, Kolhapur',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L002',
    name: 'Suresh Pawar',
    phone: '+91 98765 43211',
    skills: ['Harvesting', 'Threshing'],
    wageExpected: 500,
    rating: 4.8,
    experienceYears: 12,
    location: {
      latitude: 16.5940,
      longitude: 74.9200,
      address: 'Ichalkaranji, Kolhapur',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L003',
    name: 'Rajesh More',
    phone: '+91 98765 43212',
    skills: ['Weeding', 'Planting', 'Irrigation'],
    wageExpected: 400,
    rating: 4.2,
    experienceYears: 5,
    location: {
      latitude: 16.5880,
      longitude: 74.9100,
      address: 'Hatkanangale',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L004',
    name: 'Vijay Shinde',
    phone: '+91 98765 43213',
    skills: ['Plowing', 'Planting'],
    wageExpected: 550,
    rating: 4.9,
    experienceYears: 15,
    location: {
      latitude: 16.5960,
      longitude: 74.9250,
      address: 'Gadhinglaj',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L005',
    name: 'Prakash Patil',
    phone: '+91 98765 43214',
    skills: ['Spraying', 'Irrigation', 'Weeding'],
    wageExpected: 420,
    rating: 4.4,
    experienceYears: 6,
    location: {
      latitude: 16.5850,
      longitude: 74.9050,
      address: 'Shirol',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L006',
    name: 'Madhukar Gaikwad',
    phone: '+91 98765 43215',
    skills: ['Transplanting', 'Harvesting'],
    wageExpected: 380,
    rating: 4.0,
    experienceYears: 4,
    location: {
      latitude: 16.5900,
      longitude: 74.9150,
      address: 'Kagal',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L007',
    name: 'Santosh Jadhav',
    phone: '+91 98765 43216',
    skills: ['Harvesting', 'Threshing', 'Planting'],
    wageExpected: 480,
    rating: 4.6,
    experienceYears: 10,
    location: {
      latitude: 16.5980,
      longitude: 74.9300,
      address: 'Chandgad',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L008',
    name: 'Dilip Kumbhar',
    phone: '+91 98765 43217',
    skills: ['Weeding', 'Spraying'],
    wageExpected: 400,
    rating: 4.3,
    experienceYears: 7,
    location: {
      latitude: 16.5820,
      longitude: 74.9000,
      address: 'Panhala',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L009',
    name: 'Anil Desai',
    phone: '+91 98765 43218',
    skills: ['Planting', 'Irrigation', 'Plowing'],
    wageExpected: 460,
    rating: 4.7,
    experienceYears: 9,
    location: {
      latitude: 16.5860,
      longitude: 74.9120,
      address: 'Radhanagari',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L010',
    name: 'Ganesh Bhosale',
    phone: '+91 98765 43219',
    skills: ['Harvesting', 'Weeding', 'Transplanting'],
    wageExpected: 430,
    rating: 4.1,
    experienceYears: 5,
    location: {
      latitude: 16.5925,
      longitude: 74.9220,
      address: 'Karad Road',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L011',
    name: 'Hanuman Salunkhe',
    phone: '+91 98765 43220',
    skills: ['Threshing', 'Plowing'],
    wageExpected: 520,
    rating: 4.8,
    experienceYears: 14,
    location: {
      latitude: 16.5790,
      longitude: 74.8980,
      address: 'Ajra',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L012',
    name: 'Nitin Mane',
    phone: '+91 98765 43221',
    skills: ['Spraying', 'Irrigation'],
    wageExpected: 410,
    rating: 4.2,
    experienceYears: 6,
    location: {
      latitude: 16.6010,
      longitude: 74.9350,
      address: 'Bhudargad',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L013',
    name: 'Mahesh Gurav',
    phone: '+91 98765 43222',
    skills: ['Harvesting', 'Planting', 'Weeding'],
    wageExpected: 440,
    rating: 4.5,
    experienceYears: 8,
    location: {
      latitude: 16.5870,
      longitude: 74.9080,
      address: 'Shahuwadi',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L014',
    name: 'Sunil Kamble',
    phone: '+91 98765 43223',
    skills: ['Plowing', 'Transplanting'],
    wageExpected: 470,
    rating: 4.6,
    experienceYears: 11,
    location: {
      latitude: 16.5930,
      longitude: 74.9180,
      address: 'Kolhapur Rural',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L015',
    name: 'Ashok Chavan',
    phone: '+91 98765 43224',
    skills: ['Irrigation', 'Spraying', 'Weeding'],
    wageExpected: 395,
    rating: 4.0,
    experienceYears: 3,
    location: {
      latitude: 16.5910,
      longitude: 74.9140,
      address: 'Kasba Bawda',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
  {
    laborId: 'L016',
    name: 'Sachin Dhavale',
    phone: '+91 98765 43225',
    skills: ['Harvesting', 'Threshing', 'Plowing'],
    wageExpected: 510,
    rating: 4.9,
    experienceYears: 13,
    location: {
      latitude: 16.5890,
      longitude: 74.9160,
      address: 'Malkapur',
      district: 'Kolhapur',
      state: 'Maharashtra',
    },
  },
];
