import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../../../theme/tokens';

export const ownerHomeStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  scrollContent: { padding: spacing.xl, paddingBottom: 100 },
  sectionGap: { height: spacing.lg },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    marginLeft: spacing.sm,
  },
  statsRow: { flexDirection: 'row', marginBottom: spacing.lg },
  statsSpacer: { width: spacing.md },
  recentActivityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  recentActivityTitle: { fontSize: 18, fontWeight: '700', color: colors.textPrimary },
  viewAllText: { fontSize: 14, fontWeight: '600', color: colors.success },
  reportCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reportIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.softBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  reportContent: { flex: 1 },
  reportTitle: { fontSize: 16, fontWeight: '700', color: colors.textPrimary },
  reportSubtitle: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
  quickActionsHeader: { marginTop: spacing.lg, marginBottom: spacing.md },
  quickActionsTitle: { fontSize: 16, fontWeight: '700', color: colors.textPrimary },
  quickActionsRow: { flexDirection: 'row', gap: spacing.md },
  quickActionBtn: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.lg,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  quickActionIconWrap: { marginBottom: spacing.sm },
  quickActionLabel: { fontSize: 14, fontWeight: '600', color: colors.textPrimary },
});
