import { CropCycle } from '../types';

export const MOCK_CROP_CYCLES: CropCycle[] = [
  {
    cropCycleId: 'CC001',
    landId: 'initial-1',
    farmerId: 'F001',
    cropName: 'Sugarcane',
    plotName: 'Kagal Village Plot A',
    areaAcres: 5.0,
    landlord: 'Mr. Sanjay Patil',
    status: 'active',
  },
  {
    cropCycleId: 'CC002',
    landId: 'initial-2',
    farmerId: 'F001',
    cropName: 'Wheat',
    plotName: 'Murgud Road Plot B',
    areaAcres: 3.5,
    landlord: 'Mrs. Sunita Deshmukh',
    status: 'active',
  },
  {
    cropCycleId: 'CC003',
    landId: 'initial-3',
    farmerId: 'F002',
    cropName: 'Paddy',
    plotName: 'Radhanagari Field C',
    areaAcres: 10.0,
    landlord: 'Self Owned',
    status: 'active',
  },
  {
    cropCycleId: 'CC004',
    landId: 'initial-1',
    farmerId: 'F002',
    cropName: 'Cotton',
    plotName: 'Kasba Cotton Plot',
    areaAcres: 4.0,
    landlord: 'Suresh Yadav',
    status: 'active',
  },
  {
    cropCycleId: 'CC005',
    landId: 'initial-2',
    farmerId: 'F001',
    cropName: 'Tomato',
    plotName: 'Banmankhi Tomato',
    areaAcres: 2.5,
    landlord: 'Ramesh Kumar',
    status: 'active',
  },
];
