import { ColdStorage } from '../types';
import { market } from '../theme/marketTokens';

/**
 * Nearby cold storages a farmer can book into when a price-crash alert fires.
 * Each carries a feature list that drives the detail page + booking eligibility.
 */
export const MOCK_COLD_STORAGES: ColdStorage[] = [
  {
    id: 'cs1',
    name: 'Sahyadri Cold Chain',
    location: 'Dharwad Industrial Area',
    distanceKm: 6.2,
    rating: 4.7,
    reviews: 214,
    verified: true,
    availableCapacityMT: 320,
    totalCapacityMT: 1200,
    ratePerKgPerDay: 0.12,
    tempRange: '2°C – 8°C',
    commodities: 'Multi-commodity',
    openHours: 'Open 24×7',
    image: '❄️',
    tone: market.b2,
    highlights: ['Pre-cooling', '24×7 power', 'Insurance'],
    features: [
      { icon: 'snow', label: 'Pre-cooling chamber', available: true },
      { icon: 'flash', label: '24×7 power backup', available: true },
      { icon: 'shield-checkmark', label: 'Insurance covered', available: true },
      { icon: 'cube', label: 'Sorting & grading', available: true },
      { icon: 'car', label: 'Loading dock + reefer', available: true },
      { icon: 'thermometer', label: 'IoT temp monitoring', available: true },
    ],
  },
  {
    id: 'cs2',
    name: 'Krishna Agro Storage',
    location: 'Hubli Bypass Road',
    distanceKm: 12.5,
    rating: 4.4,
    reviews: 138,
    verified: true,
    availableCapacityMT: 140,
    totalCapacityMT: 600,
    ratePerKgPerDay: 0.1,
    tempRange: '4°C – 10°C',
    commodities: 'Fruits & vegetables',
    openHours: '6 AM – 10 PM',
    image: '🧊',
    tone: market.g3,
    highlights: ['Lowest price', 'Sorting', 'Insurance'],
    features: [
      { icon: 'snow', label: 'Pre-cooling chamber', available: false },
      { icon: 'flash', label: '24×7 power backup', available: true },
      { icon: 'shield-checkmark', label: 'Insurance covered', available: true },
      { icon: 'cube', label: 'Sorting & grading', available: true },
      { icon: 'car', label: 'Loading dock + reefer', available: false },
      { icon: 'thermometer', label: 'IoT temp monitoring', available: true },
    ],
  },
  {
    id: 'cs3',
    name: 'Belagavi Freshpack',
    location: 'Belagavi APMC Yard',
    distanceKm: 71.0,
    rating: 4.8,
    reviews: 302,
    verified: true,
    availableCapacityMT: 480,
    totalCapacityMT: 1500,
    ratePerKgPerDay: 0.14,
    tempRange: '0°C – 6°C',
    commodities: 'Export-grade · Multi',
    openHours: 'Open 24×7',
    image: '🏭',
    tone: market.a3,
    highlights: ['Export grade', 'At best mandi', 'Reefer'],
    features: [
      { icon: 'snow', label: 'Pre-cooling chamber', available: true },
      { icon: 'flash', label: '24×7 power backup', available: true },
      { icon: 'shield-checkmark', label: 'Insurance covered', available: true },
      { icon: 'cube', label: 'Sorting & grading', available: true },
      { icon: 'car', label: 'Loading dock + reefer', available: true },
      { icon: 'thermometer', label: 'IoT temp monitoring', available: true },
    ],
  },
  {
    id: 'cs4',
    name: 'Gadag Farmer Coop Store',
    location: 'Gadag Town',
    distanceKm: 44.0,
    rating: 4.1,
    reviews: 76,
    verified: false,
    availableCapacityMT: 60,
    totalCapacityMT: 250,
    ratePerKgPerDay: 0.08,
    tempRange: '6°C – 12°C',
    commodities: 'General produce',
    openHours: '7 AM – 8 PM',
    image: '🏬',
    tone: market.n4,
    highlights: ['Cheapest', 'Coop run'],
    features: [
      { icon: 'snow', label: 'Pre-cooling chamber', available: false },
      { icon: 'flash', label: '24×7 power backup', available: false },
      { icon: 'shield-checkmark', label: 'Insurance covered', available: false },
      { icon: 'cube', label: 'Sorting & grading', available: false },
      { icon: 'car', label: 'Loading dock + reefer', available: false },
      { icon: 'thermometer', label: 'IoT temp monitoring', available: false },
    ],
  },
];

/** Default produce the farmer is looking to store (carried from the crash alert). */
export const DEFAULT_STORE_INTENT = {
  cropName: 'Tomato',
  quantityKg: 1200,
  recommendedDays: 15,
  /** Expected price recovery used to frame the booking value. */
  expectedRecoveryPerKg: 8,
};
